---
- name: My Test Playbook
  hosts: localhost
  become: true
  
  tasks:
  - name: Basically "apt-get update"
    ansible.builtin.apt:
      update_cache: true
 
  - name: Install NGINX Packages
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: true
  
  - name: Install software-properties-common
    ansible.builtin.apt:
      name: software-properties-common
      state: present
      update_cache: true
  - name: Install ppa:ondrej/php
    ansible.builtin.apt_repository:
      repo: ppa:ondrej/php
      update_cache: true    
    register: results
  - debug:
      var: results
  - name: Install PHP 8.1 FPM
    ansible.builtin.apt:
      name: php8.1-fpm
      state: present
      update_cache: true    
      
  - name: checking
    ansible.builtin.command: 
      cmd: php -v  
    register: command_output
  - name: command output
    ansible.builtin.debug:
      var: command_output.stdout_lines
      
# --------------------------Installing Mysql  and dependencies

  - name: Installing Mysql  and dependencies
    package:
     name: "{{item}}"
     state: present
     update_cache: yes
    loop:
      - mysql-server
      - mysql-client 
      - python3-mysqldb
      - libmysqlclient-dev
     
  - name: start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes
      
  - name: Enable remote login to mysql
    ansible.builtin.lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
      backup: yes
    notify:
      - Restart mysql
   
  - name: creating mysql user (medium_post)
    mysql_user:
      name: "{{db_user}}"
      password: "{{db_pass}}"
      priv: '*.*:ALL'
      host: '%'
      state: present
 
  - name: creating medium_db
    mysql_db:
      name: "{{db_name}}"
      state: present     
       
       
       
       
  # -------------------------- Configuration SSH
  
  - name: Отключить логин по паролю и разрешить логиниться только с помощью publickey.
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^#?AuthenticationMethods' 
      line: AuthenticationMethods publickey
      backup: yes
      
  - name: Отключить логин по паролю и разрешить логиниться только с помощью publickey.
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^#?PasswordAuthentication'
      line: PasswordAuthentication no
      backup: yes
      
  - name: Отключить логин по паролю и разрешить логиниться только с помощью publickey.
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^#?ChallengeResponseAuthentication'
      line: ChallengeResponseAuthentication no
      backup: yes  
   
  - name: Отключить логин по паролю и разрешить логиниться только с помощью publickey.
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^#?PubkeyAuthentication'
      line: PubkeyAuthentication yes
      backup: yes
      
  - name: Change Port 22 to 1234
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^#?Port 22'
      line: Port 1234
      backup: yes
      
  - name: checking sshd_config 
    ansible.builtin.command: 
      cmd: cat /etc/mysql/mysql.conf.d/mysqld.cnf      
      # cmd: cat /etc/ssh/sshd_config
    register: command_output
  - name: command output
    ansible.builtin.debug:
      var: command_output.stdout_lines
 
  handlers:
  - name: Restart mysql
    service:
      name: mysql
      state: restarted
      
  - name: Restat sshd
    service:
      name: sshd
      state: restarted
